name: ChiyogamiMonitor
version: ${project.version}
main: be4rjp.chiyogamimonitor.ChiyogamiMonitor
api-version: 1.21

#--------------------------------------
commands:
  chmonitor:
    description: Type /chmonitor help
    usage: Type /chmonitor help
    permission: chmonitor.admin
#--------------------------------------
permissions:
  chmonitor.admin:
    description: admin command.
